### ISSUE TITLE
Quick Reminder Screen - Create

### ISSUE THREAD

**Issue by anton-mcquinn** [anton-mcintosh/ACE#3]
Get the Quick Reminder screen looking like the prototype for the most part. Don't worry about the 'Home' button; we're handling that in the header for now. We don't have a back end yet, so don't worry about making anything functional. We'll dig into that later. Here is a link to vector icons that you can use with expogo: https://icons.expo.fyi/Index

**Comment by Srivathsav-v** [comment]
Completed long back.

sorry for updating lately here
